---
- hosts: localhost
  connection: local
  gather_facts: no
  vars:
    model_dir: "{{ playbook_dir }}/models"
    inventory_root: "{{ playbook_dir }}/inventory"
    key_root: "{{ playbook_dir }}/keys"
    cloud_instance: "{{ cloud_model.split('.')[0] }}"
    cloud_project: "{{ lookup('env','USER') }}"
    cloud_provider: 'aws'
    cloud_region: 'us-east-1'
    cloud_user: ec2-user
    cloud_name: "{{ cloud_instance }}.{{ cloud_project }}"
    cloud_key_name: "{{ opt_key_name | default(cloud_name) }}"
    cloud_private_key_file: "{{ key_root }}/{{ cloud_key_name }}.key"
    cloud_public_key_file: "{{ key_root }}/{{ cloud_key_name }}.key.pub"
    cloud_cidr: '10.1.0.0/16'

  tasks:
    - assert:
        that:
          - ansible_version.full | version_compare('2.5', '>=')
        msg: "This playbook requires ansible >= 2.5. You have {{ ansible_version.full }}"

    - assert:
        that:
          - cloud_model is defined
        msg: "You must specify a model, e.g. -e 'cloud_model=csr-lab1.yml'"



    - set_fact:
        cloud_provider: "{{ opt_provider_region.split('/')[0] }}"
        cloud_region: "{{ opt_provider_region.split('/')[1] }}"
      when: opt_provider_region is defined

    - block:
        - name: Create the keys directory
          file:
            path: "{{ key_root }}"
            state: directory
            mode: 0755

        - openssl_privatekey:
            path: "{{ cloud_private_key_file }}"
            type: RSA
            size: 2048
          register: key_results

        - openssl_publickey:
            path: "{{ cloud_public_key_file }}"
            privatekey_path: "{{ cloud_private_key_file }}"
            format: OpenSSH
            force: no
          when: key_results.changed
          register: public_key_results

        - set_fact:
            cloud_public_key_material: "{{ lookup('file', cloud_public_key_file) }}"
      when: cloud_public_key_material is not defined

    - name: Find the cloud model
      set_fact:
        cloud_model_file: "{{ item }}"
      with_first_found:
        - files:
            - "{{ cloud_model }}.yml"
            - "{{ cloud_model }}.yaml"
            - "{{ cloud_model }}"
          paths:
            - "{{ model_dir }}"
            - "{{ playbook_dir }}"
            - "{{ inventory_dir }}"

    - name: Read in the Cloud Model {{ cloud_model }}
      include_vars:
        file: "{{ cloud_model_file }}"

    - include_role:
        name: cloud-config
      vars:
        - cloud_vpc_name: "{{ vpc_item.name }}"
        - cloud_vpc_data: "{{ vpc_item }}"
      with_items: "{{ vpc_list | default([]) }}"
      loop_control:
        loop_var: vpc_item
      run_once: yes
