---
- hosts: localhost
  connection: local
  gather_facts: no
  vars:
    ansible_ssh_private_key_file: "keys/{{ cloud_name }}_key"
    ansible_ssh_public_key_file: "keys/{{ cloud_name }}_key.pub"

  tasks:
    - name: Make the projects directory rx
      file:
        path: keys
        state: directory
        mode: 0755

    - name: Generate SSH keys
      shell: ssh-keygen -b 2048 -t rsa -f "{{ ansible_ssh_private_key_file }}" -I "{{ cloud_name }}" -q -N ""
      args:
        creates: "{{ ansible_ssh_private_key_file }}"
      delegate_to: localhost
      run_once: yes

    # - set_fact:
    #     ansible_ssh_private_key_file: "keys/{{ cloud_name }}_key"
    #     ansible_ssh_public_key_file: "keys/{{ cloud_name }}_key.pub"
    #   delegate_to: localhost
    #   run_once: yes

    # - openssl_privatekey:
    #     path: "{{ ansible_ssh_private_key_file }}"
    #     type: RSA
    #     size: 2048
    #   delegate_to: localhost
    #   run_once: yes
    #   register: key_results
    #
    # - openssl_publickey:
    #     path: "{{ ansible_ssh_public_key_file }}"
    #     privatekey_path: "{{ ansible_ssh_private_key_file }}"
    #     format: OpenSSH
    #     force: no
    #   delegate_to: localhost
    #   run_once: yes
    #   when: key_results.changed

    - include_role:
        name: cloud-config
      vars:
        - cloud_vpc_name: "{{ vpc_item.name }}"
        - cloud_vpc_data: "{{ vpc_item }}"
      with_items: "{{ vpc_list | default([]) }}"
      loop_control:
        loop_var: vpc_item
      delegate_to: localhost
      run_once: yes
