---
- name: Read in the cloud inventory
  hosts: localhost
  connection: local
  gather_facts: False
  tags:
    - tower_cli
  vars:
    model_dir: "{{ playbook_dir }}/models"
    inventory_root: "{{ playbook_dir }}/inventory"
    key_root: "{{ playbook_dir }}/keys"
    cloud_instance: "{{ cloud_model.split('.')[0] }}"
    cloud_project: "{{ lookup('env','USER') }}"
    cloud_provider: 'aws'
    cloud_region: 'us-east-1'
    cloud_user: ec2-user
    cloud_name: "{{ cloud_instance }}.{{ cloud_project }}"
    cloud_key_name: "{{ cloud_name }}"
    cloud_private_key_file: "{{ key_root }}/{{ cloud_key_name }}.key"
    cloud_public_key_file: "{{ key_root }}/{{ cloud_key_name }}.key.pub"
    cloud_cidr: '10.1.0.0/16'

  tasks:
    - assert:
        that:
          - cloud_model is defined
        msg: "You must specify a model, e.g. -e 'cloud_model=csr-lab1.yml'"

    - set_fact:
        cloud_provider: "{{ opt_provider_region.split('/')[0] }}"
        cloud_region: "{{ opt_provider_region.split('/')[1] }}"
      when: opt_provider_region is defined

    - name: Find the cloud model
      set_fact:
        cloud_model_file: "{{ item }}"
      with_first_found:
        - files:
            - "{{ cloud_model }}.yml"
            - "{{ cloud_model }}.yaml"
            - "{{ cloud_model }}"
          paths:
            - "{{ model_dir }}"
            - "{{ playbook_dir }}"
            - "{{ inventory_dir }}"

    - name: Read in the Cloud Model {{ cloud_model }}
      include_vars:
        file: "{{ cloud_model_file }}"

    - include_role:
        name: cloud-facts
      vars:
        - cloud_vpc_name: "{{ vpc_item.name }}"
        - cloud_vpc_data: "{{ vpc_item }}"
      with_items: "{{ vpc_list | default([]) }}"
      tasks_from: instances
      loop_control:
        loop_var: vpc_item
      delegate_to: localhost
      run_once: yes

- hosts: "control_hosts:&{{ cloud_name }}"
  become: yes
  vars:
    model_dir: "{{ playbook_dir }}/models"
    inventory_root: "{{ playbook_dir }}/inventory"
    key_root: "{{ playbook_dir }}/keys"
    cloud_instance: "{{ cloud_model.split('.')[0] }}"
    cloud_project: "{{ lookup('env','USER') }}"
    cloud_provider: 'aws'
    cloud_region: 'us-east-1'
    cloud_user: ec2-user
    cloud_name: "{{ cloud_instance }}.{{ cloud_project }}"
    cloud_key_name: "{{ cloud_name }}"
    cloud_vars_file: "{{ key_root }}/{{ cloud_name }}.yml"
    cloud_private_key_file: "{{ key_root }}/{{ cloud_key_name }}.key"
    cloud_public_key_file: "{{ key_root }}/{{ cloud_key_name }}.key.pub"
    cloud_cidr: '10.1.0.0/16'
    demo_username: 'labuser'
    demo_repo_name: 'an-demos'
    demo_repo_root: 'https://github.com/network-automation'
    demo_root: "~{{ demo_username }}/{{ demo_repo_name }}"
    ansible_tower_admin_pass: "{{ lookup('password', '/tmp/passwordfile chars=digits') }}"
    use_ansible_devel: no

  tasks:
    # - name: Update all packages
    #   yum:
    #     name: '*'
    #     state: latest

    - name: Read in the cloud vars
      include_vars:
        file: "{{ cloud_vars_file }}"
        name: cloud_vars
      tags:
        - tower_cli

    - name: Create the lab user
      user:
        name: "{{ demo_username }}"
        comment: "Lab User"
        password: '$6$2qJit.8h6RYzzGpF$DCyv0YRGCN0FTqO0e.MjphP1xooyzOB1sloxzSaA/Db8Br.r.Fip.sEc9bV1vfMqzhzBL0RAQPskpzwXh10mU0'
        uid: 2000
        group: wheel

    - name: Allow 'wheel' group to have passwordless sudo
      lineinfile:
        dest: /etc/sudoers
        state: present
        regexp: '^%wheel'
        line: '%wheel ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'

    - name: Create the .ssh directory
      file:
        path: "~{{ demo_username }}/.ssh"
        state: directory
        owner: "{{ demo_username }}"
        mode: 0700

    - name: Copy the ssh private key
      copy:
        src: "{{ ansible_ssh_private_key_file }}"
        dest: "~{{ demo_username }}/.ssh/id_rsa"
        owner: "{{ demo_username }}"
        mode: 0600

    - name: Copy the ssh public key
      copy:
        src: "{{ ansible_ssh_private_key_file }}.pub"
        dest: "~{{ demo_username }}/.ssh/id_rsa.pub"
        owner: "{{ demo_username }}"
        mode: 0600

    - name: create the ~/.ssh/config
      blockinfile:
        path: "~{{ demo_username }}/.ssh/config"
        create: yes
        owner: "{{ demo_username }}"
        block: |
          Host *
          StrictHostKeyChecking no

    - name: create the ~/.ansible.cfg
      blockinfile:
        path: "~{{ demo_username }}/.ansible.cfg"
        create: yes
        owner: "{{ demo_username }}"
        block: |
          [defaults]
          host_key_checking = False

    - name: Allow password authentication
      lineinfile: dest=/etc/ssh/sshd_config
                  regexp="^PasswordAuthentication"
                  line="PasswordAuthentication yes"
                  state=present
      become: yes
      notify: Restart sshd

    - name: Enable syslog UDP
      lineinfile: dest=/etc/ssh/sshd_config
                  regexp="^PasswordAuthentication"
                  line="PasswordAuthentication yes"
                  state=present
      become: yes
      notify: Restart rsyslogd

    - name: Enable syslog
      blockinfile:
        path: /etc/rsyslog.conf
        block: |
          $ModLoad imudp
          $UDPServerRun 514
          $ModLoad imtcp
          $InputTCPServerRun 514
      notify: Restart rsyslog

    - name: Disable certificate checking for Python
      lineinfile:
        dest: "~{{ demo_username }}/.bash_profile"
        line: "export PYTHONHTTPSVERIFY=0"

    - name: Check to see if the .tower_cli.cfg exists
      stat:
        path: "~{{ demo_username }}/.tower_cli.cfg"
      register: stat_results
      become_user: "{{ demo_username }}"

    - name: create the ~/.tower_cli.cfg
      blockinfile:
        path: "~{{ demo_username }}/.tower_cli.cfg"
        create: yes
        owner: "{{ demo_username }}"
        mode: 0600
        block: |
          host: localhost
          username: admin
          password: {{ cloud_vars.password }}
      when: stat_results.stat.exists == false
      become_user: "{{ demo_username }}"

    # - name: Get the password that we've previously specified for Tower
    #   slurp:
    #     src: "~{{ demo_username }}/.tower_cli.cfg"
    #   register: tower_creds
    #   become_user: "{{ demo_username }}"
    #
    # - debug: msg="{{ tower_creds['content'] | b64decode }}"
    #
    # - set_fact:
    #     tower_creds: "{{ tower_creds['content'] | b64decode | to_yaml }}"
    #
    # - debug: var=tower_creds
    #
    # - meta: end_play

    - name: Add EPEL repository
      yum_repository:
        name: epel
        description: EPEL YUM repo
        baseurl: https://download.fedoraproject.org/pub/epel/$releasever/$basearch/
        gpgkey: https://mirror.steadfast.net/epel/RPM-GPG-KEY-EPEL-7

    - name: Remove out of date Yum packages
      yum:
        name: "{{ item }}"
        state: absent
      with_items:
        - python-requests
        - pyOpenSSL

    - name: Install YUM packages
      yum:
        name: "{{ item }}"
        state: latest
      with_items:
        - python2-pip
        - git

    - name: Install YUM packages
      yum:
        name: ansible
        state: latest
      when: use_ansible_devel|bool == false

    - include_role:
        name: ansible-tower
      vars:
        ansible_tower_version: '3.2.2'
      tags:
        - tower

    - name: Install Ansible Devel
      pip:
        name: git+git://github.com/ansible/ansible.git
        state: latest
      when: use_ansible_devel|bool

    - name: Install PIP packages
      pip:
        name: "{{ item }}"
        state: latest
      with_items:
        - "setuptools>=1.4"
        - f5-sdk
        - bigsuds
        - pan-python
        - pandevice
        - pexpect
        - requests
        - pyopenssl
        - netaddr
        - "ansible-tower-cli==3.1.8"
        - xmltodict
        - ncclient

    - name: Install Ansible Devel into Tower's virtualenv
      pip:
        name: git+git://github.com/ansible/ansible.git
        state: latest
        virtualenv_command: /var/lib/awx/venv/ansible/bin/activate
      when: use_ansible_devel|bool

    - name: Install PIP packages into Tower's virtualenv
      pip:
        name: "{{ item }}"
        state: latest
        virtualenv_command: /var/lib/awx/venv/ansible/bin/activate
      with_items:
        - "setuptools>=1.4"
        - f5-sdk
        - bigsuds
        - pan-python
        - pandevice
        - pexpect
        - requests
        - pyopenssl
        - netaddr
        - "ansible-tower-cli==3.1.8"
        - xmltodict
        - ncclient

    - name: Add IP addresses to /etc/hosts
      lineinfile:
        dest: /etc/hosts
        line: "{{ hostvars[item].ansible_host }} {{ hostvars[item].inventory_hostname.split('.')[0] }}"
        state: present
      with_items: "{{ groups.all }}"

    - name: Create the git user
      user:
        name: git
        comment: git
        password: '$6$2qJit.8h6RYzzGpF$DCyv0YRGCN0FTqO0e.MjphP1xooyzOB1sloxzSaA/Db8Br.r.Fip.sEc9bV1vfMqzhzBL0RAQPskpzwXh10mU0'
        uid: 2001
        group: wheel

    - name: Create the .ssh directory
      file:
        path: "~git/.ssh"
        state: directory
        owner: git
        mode: 0700

    - name: Create git user's authorized_keys
      copy:
        src: "{{ ansible_ssh_private_key_file }}.pub"
        dest: "~git/.ssh/authorized_keys"
        owner: git
        mode: 0600

    - name: Create the {{ demo_repo_name }} local repo
      command: git clone --bare "{{ demo_repo_root }}/{{ demo_repo_name }}.git"
      args:
        creates: "/home/git/{{ demo_repo_name }}.git/HEAD"
      become_user: git

    - name: Install the {{ demo_repo_name }}
      git:
        repo: "git@localhost:/home/git/{{ demo_repo_name }}.git"
        dest: "{{ demo_root }}"
        force: yes
      become_user: "{{ demo_username }}"

    - name: Remove inventory from .gitignore
      lineinfile:
        path: "~{{ demo_username }}/{{ demo_repo_name }}/.gitignore"
        state: absent
        regexp: 'inventory'
      become_user: "{{ demo_username }}"

    - name: Create the inventory directory
      file:
        path: "{{ item }}"
        state: directory
        owner: "{{ demo_username }}"
        mode: 0755
        recurse: yes
      with_items:
        - "{{ demo_root }}/inventory"
        - "{{ demo_root }}/inventory/host_vars"
        - "{{ demo_root }}/inventory/group_vars"

    - name: Create the inventory file on the control node(s)
      template:
        src: control-inventory.j2
        dest: "{{ demo_root }}/inventory/hosts"
        owner: "{{ demo_username }}"

    - name: Create the group_vars files
      copy:
        src: group_vars
        dest: "{{ demo_root }}/inventory"
        owner: "{{ demo_username }}"

    - name: Create the host_vars directories
      file:
        path: "{{ demo_root }}/inventory/host_vars/{{ item.split('.')[0] }}"
        state: directory
        owner: "{{ demo_username }}"
        mode: 0755
      when: hostvars[item].interfaces is defined
      with_items: "{{ groups.network }}"

    - name: Create the interfaces files
      template:
        src: "{{ playbook_dir }}/templates/interfaces.j2"
        dest: "{{ demo_root }}/inventory/host_vars/{{ item.split('.')[0] }}/interfaces.yml"
        owner: "{{ demo_username }}"
      when: hostvars[item].interfaces is defined
      with_items: "{{ groups.network }}"

    - name: Add the inventory changes
      command: git add inventory
      args:
        chdir: "{{ demo_root }}"
      become_user: "{{ demo_username }}"

    - name: Commit the inventory changes
      command: git commit -a -m "Added inventory"
      args:
        chdir: "{{ demo_root }}"
      become_user: "{{ demo_username }}"

    - name: Push the inventory changes
      command: git push origin master
      args:
        chdir: "{{ demo_root }}"
      become_user: "{{ demo_username }}"

    - name: Add tower "{{ demo_username }}" account
      command: tower-cli user create --username "{{ demo_username }}" --password "{{ cloud_vars.password }}" --is-superuser yes --email labuser@ansible.com
      become_user: "{{ demo_username }}"
      tags:
        - tower
        - tower_cli

    - name: Add tower git credential
      command: tower-cli credential create --name git --kind scm --organization Default --ssh-key-data ~/.ssh/id_rsa
      become_user: "{{ demo_username }}"
      tags:
        - tower
        - tower_cli

    - name: Add tower ssh credential
      command: tower-cli credential create --name tower --kind ssh --organization Default --ssh-key-data ~/.ssh/id_rsa
      become_user: "{{ demo_username }}"
      tags:
        - tower
        - tower_cli

    - name: Add tower demo repo
      command: tower-cli project create --name an-demos --scm-type git --scm-url git@localhost:/home/git/an-demos
      become_user: "{{ demo_username }}"
      tags:
        - tower
        - tower_cli

    # - name: Add tower git credential
    #   tower_credential:
    #     name: git
    #     description: git
    #     organization: Default
    #     kind: scm
    #     state: present
    #     ssh_key_data: "~{{ demo_username }}/.ssh/id_rsa"
    #     tower_config_file: "~{{ demo_username }}/.tower_cli.cfg"
    #   delegate_to: "{{ ansible_host }}"
    #   become: "{{ demo_username }}"
    #   tags:
    #     - tower
    #     - tower_cli
    #
    # - name: Add tower machine credential
    #   tower_credential:
    #     name: tower
    #     description: tower
    #     organization: Default
    #     kind: ssh
    #     state: present
    #     ssh_key_data: "~{{ demo_username }}/.ssh/id_rsa"
    #     tower_config_file: "~{{ demo_username }}/.tower_cli.cfg"
    #   delegate_to: "{{ ansible_host }}"
    #   become: "{{ demo_username }}"
    #   tags:
    #     - tower
    #     - tower_cli

    - debug: msg="Control node public IP = {{ ansible_host }}"

  handlers:
    - name: Restart sshd
      systemd:
        name: sshd
        state: restarted
      become: yes
    - name: Restart rsyslog
      systemd:
        name: rsyslog
        state: restarted
      become: yes
