---
- name: Configure the control node
  hosts: control

  tasks:
    - name: Update all packages
      yum:
        name: '*'
        state: latest
      become: yes

    - name: Install EPEL repository
      yum:
        name: epel-release
        state: present
      become: yes

    - name: Install YUM packages
      yum:
        name: "{{ item }}"
        state: latest
      with_items:
        - python-pip
        - python-devel
        - python-netaddr
        - openssl-devel
        - sudo
        - git
        - gcc

      become: yes

    - name: Install Ansible
      pip:
        name: 'git+git://github.com/ansible/ansible.git'
      become: yes

    - name: Install PIP packages
      pip:
        name: "{{ item }}"
        state: latest
      with_items:
        #- ansible
        - paramiko
        - PyYAML
        - Jinja2
        - httplib2
        - six
        #- shade
        - jxmlease
        - ncclient
        - pexpect
        - f5-sdk
        - bigsuds
        - pan-python
        - pandevice
        - requests
        - pyopenssl
      become: yes

    - name: Install the an-demo-kit
      git:
        repo: https://github.com/ismc/an-demo-kit.git
        dest: "~{{ ansible_ssh_user }}/an-demo-kit"

    - name: Create the inventory directory
      file:
        path: "~{{ ansible_ssh_user }}/an-demo-kit/inventory/"
        state: directory
        owner: "{{ ansible_ssh_user }}"
        mode: 0755

    - name: Create the keys directory
      file:
        path: "~{{ ansible_ssh_user }}/an-demo-kit/keys"
        state: directory
        owner: "{{ ansible_ssh_user }}"
        mode: 0755

    - name: Copy the ssh key
      copy:
        src: "{{ ansible_ssh_private_key_file }}"
        dest: "~{{ ansible_ssh_user }}/an-demo-kit/keys"
        owner: "{{ ansible_ssh_user }}"
        mode: 0600

    - name: Copy the inventory
      copy:
        src: "{{ inventory_dir }}"
        dest: "~{{ ansible_ssh_user }}/an-demo-kit/inventory/"
        owner: "{{ ansible_ssh_user }}"
        mode: 0644

    - name: create the .ansible.cfg
      blockinfile:
        path: "~{{ ansible_ssh_user }}/.ansible.cfg"
        create: yes
        block: |
          [defaults]
          host_key_checking = False

    - debug: msg="Control node public IP':' {{ ansible_host }}"
