---
- name: Get the cloud facts
  hosts: localhost
  tasks:
    - include_role:
        name: cloud-facts
      vars:
        - cloud_vpc_name: "{{ vpc_item.name }}"
        - cloud_vpc_data: "{{ vpc_item }}"
      with_items: "{{ vpc_list | default([]) }}"
      tasks_from: instances
      loop_control:
        loop_var: vpc_item
      delegate_to: localhost
      run_once: yes

- name: Create vars files
  hosts: control
  tasks:
    - name: Update all packages
      yum:
        name: '*'
        state: latest
      become: yes

    - name: Install EPEL repository
      yum:
        name: epel-release
        state: present
      become: yes

    - name: Install YUM packages
      yum:
        name: "{{ item }}"
        state: latest
      with_items:
        - python-pip
        - python-devel
        - python-netaddr
        - openssl-devel
        - sudo
        - git
        - gcc

      become: yes

    - name: Install Ansible
      pip:
        name: 'git+git://github.com/ansible/ansible.git'
      become: yes

    - name: Install PIP packages
      pip:
        name: "{{ item }}"
        state: latest
      with_items:
        #- ansible
        - paramiko
        - PyYAML
        - Jinja2
        - httplib2
        - six
        #- shade
        - jxmlease
        - ncclient
        - pexpect
        - f5-sdk
        - bigsuds
        - pan-python
        - pandevice
        - requests
        - pyopenssl
      become: yes

    - set_fact:
        demo_kit_root: '~{{ ansible_ssh_user }}/an-demo-kit'

    - name: Install the an-demo-kit
      git:
        repo: https://github.com/ismc/an-demo-kit.git
        dest: "{{ demo_kit_root }}"

    - name: Create the inventory directory
      file:
        path: "{{ demo_kit_root }}/inventory/"
        state: directory
        owner: "{{ ansible_ssh_user }}"
        mode: 0755

    - name: Create the inventory directory
      file:
        path: "{{ item }}"
        state: directory
        mode: 0755
      with_items:
        - "{{ demo_kit_root }}/inventory"
        - "{{ demo_kit_root }}/inventory/host_vars"
        - "{{ demo_kit_root }}/inventory/group_vars"

    - name: Create the inventory file on the control node(s)
      template:
        src: "{{ playbook_dir }}/templates/control-inventory.j2"
        dest: "{{ demo_kit_root }}/inventory/hosts"

    # - name: Create the keys directory
    #   file:
    #     path: "~{{ ansible_ssh_user }}/an-demo-kit/keys"
    #     state: directory
    #     owner: "{{ ansible_ssh_user }}"
    #     mode: 0755

    - name: Copy the ssh key
      copy:
        src: "{{ ansible_ssh_private_key_file }}"
        dest: "~{{ ansible_ssh_user }}/.ssh/id_rsa"
        owner: "{{ ansible_ssh_user }}"
        mode: 0600

    # - name: Copy the inventory
    #   copy:
    #     src: "{{ inventory_dir }}"
    #     dest: "{{ demo_kit_root }}/inventory/"
    #     owner: "{{ ansible_ssh_user }}"
    #     mode: 0644

    - name: create the .ansible.cfg
      blockinfile:
        path: "~{{ ansible_ssh_user }}/.ansible.cfg"
        create: yes
        block: |
          [defaults]
          host_key_checking = False

    - debug: msg="Control node public IP':' {{ ansible_host }}"
