---
- name: Set the interface name
  set_fact:
    interface_name: "{{ cloud_interface_item.1.name | default('eth'~cloud_interface_item.0) }}"

- name: Build the interface dict
  set_fact:
    interface_item:
      private_ip_address: "{{ instance_interface_facts[cloud_interface_item.0].private_ip_address }}"
  register: interface_facts

- name: Add the interface to the interfaces dict
  set_fact:
    instance_interfaces: "{{ instance_interfaces | combine({interface_name: interface_item}) }}"
