---
- set_fact:
    provider:
      # username: ec2-user
      # host: "{{ ansible_host }}"
      # ssh_keyfile: "./{{ cloud_name }}_key"
      authorize: yes

- name: configure hostname and domain name
  eos_system:
    provider: "{{ provider }}"
    hostname: "{{ inventory_hostname }}"
    domain_name: "{{ domain_search | default(omit) }}"
    domain_search: "{{ domain_search | default(omit) }}"
    lookup_source: "{{ lookup_source | default(omit) }}"
    name_servers: "{{ name_servers | default(omit) }}"
- name: configure the login banner
  eos_banner:
    provider: "{{ provider }}"
    banner: login
    text: "{{ network_banner }}"
    state: present
  when: network_banner is defined
