---
- name: Enable Netconf service
  iosxr_netconf:
    netconf_port: 830
    netconf_vrf: 'default'
    state: present
  connection: network_cli

- name: configure hostname and domain name
  iosxr_system:
    hostname: "{{ inventory_hostname }}"
    domain_name: "{{ domain_search | default(omit) }}"
    domain_search: "{{ domain_search | default(omit) }}"
    lookup_source: "{{ lookup_source | default(omit) }}"
    name_servers: "{{ name_servers | default(omit) }}"
  connection: netconf

- name: configure the login banner
  iosxr_banner:
    banner: login
    text: "{{ network_banner }}"
    state: present
  connection: netconf
  when: network_banner is defined
