---


- name: Configure root password and enable netconf
  junos_config:
    lines:
      - set system root-authentication encrypted-password itdontmatter
      - set system services netconf ssh
    comment: enable netconf
    confirm_commit: yes
  connection: netconf

# - name: Enable netconf service on port 830
#   junos_netconf:
#     listens_on: 830
#     state: present

- name: configure hostname and domain name
  junos_system:
    hostname: "{{ system_hostname }}"
    #domain_name: "{{ domain_search | default(omit) }}"
    domain_search: "{{ domain_search | default(omit) }}"
    lookup_source: "{{ lookup_source | default(omit) }}"
    name_servers: "{{ name_servers | default(omit) }}"
  connection: netconf

- name: configure the login banner
  junos_banner:
    banner: login
    text: "{{ network_banner }}"
    state: present
  connection: netconf
  when: network_banner is defined
