---
- name: Enable the interfaces
  ios_interface:
    name: "{{ item.key }}"
    enabled: True
  when: item.value.private_ip_address | ipaddr
  with_dict: "{{ interfaces }}"

- name: Add interfaces to the VRF
  ios_vrf:
    name: "{{ item.name }}"
    interfaces: "{{ item.interfaces }}"
  with_items: "{{ vrf_list | default([]) }}"

- name: Set Interface IP
  ios_l3_interface:
    name: "{{ item.key }}"
    ipv4: "{{ item.value.private_ip_address }}/24"
  when: item.value.private_ip_address | ipaddr
  with_dict: "{{ interfaces }}"
