---
- name: Enable the interfaces
  ios_interface:
    name: "{{ item.name }}"
    enabled: True
  when: item.private_ip_address | ipaddr
  with_items: "{{ interfaces }}"

- name: Add interfaces to the VRF
  ios_vrf:
    name: "{{ item.name }}"
    interfaces: "{{ item.interfaces }}"
  with_items: "{{ vrf_list | default([]) }}"

- name: Set Interface IP
  ios_l3_interface:
    name: "{{ item.name }}"
    ipv4: "{{ item.private_ip_cidr }}"
  when: item.private_ip_cidr | ipaddr
  with_items: "{{ interfaces }}"
