---
- hosts: routers
  connection: network_cli
  gather_facts: no

  tasks:
    - name: configure hostname and domain name
      net_system:
        hostname: "{{ inventory_hostname }}"
        domain_name: "{{ domain_search | default(omit) }}"
        domain_search: "{{ domain_search | default(omit) }}"
        lookup_source: "{{ lookup_source | default(omit) }}"
        name_servers: "{{ name_servers | default(omit) }}"

    - name: configure the login banner
      net_banner:
        banner: "{{ 'motd' if ansible_network_os == 'nxos' else 'login' }}"
        text: "{{ network_banner }}"
        state: present
      when: network_banner is defined
