---
- hosts: network
  connection: local
  gather_facts: no
  vars:
    prefix_list: 199.66.188.0/24

  tasks:
    - include_role:
        name: find-prefix-list
      vars:
        find_prefix_cidr: "{{ prefix_list }}"

    - debug: msg="Prefix list {{ prefix_list }} found in {{ found_prefix_list }}"
      when: found_prefix_list != ''
