- include_tasks: get-token.yml
  when: tower_api_token is not defined

- include_tasks: get-hosts.yml
  when: tower_api_host_map is not defined

# - name: Get host {{ tower_api_host_name }}
#   uri:
#     url: "https://{{ tower_api_endpoint }}/api/v2/hosts/?name={{ tower_api_host_name }}"
#     method: GET
#     headers:
#       Authorization: "Token {{ tower_api_token }}"
#     body_format: json
#     validate_certs: "{{ validate_certs }}"
#     return_content: yes
#   ignore_errors: no
#   register: get_result

- block:
    - name: Add host {{ tower_api_host_name }}
      uri:
        url: "https://{{ tower_api_endpoint }}/api/v2/hosts/"
        method: POST
        headers:
          Authorization: "Token {{ tower_api_token }}"
        body:
          name: "{{ tower_api_host_name }}"
          inventory: "{{ tower_api_inventory_id }}"
          variables: "{{ tower_api_host_vars | to_json }}"
        body_format: json
        validate_certs: "{{ validate_certs }}"
        return_content: yes
        status_code: 201
      register: post_result

    - set_fact:
        tower_api_host_map: "{{ tower_api_host_map|default({}) | combine( { tower_api_host_name: post_result.json.id } ) }}"

  when: tower_api_host_map[tower_api_host_name] is not defined
