---
- name: Download Ansible Tower
  unarchive:
    src: "https://releases.ansible.com/ansible-tower/setup-bundle/ansible-tower-setup-bundle-{{ ansible_tower_version }}.el7.tar.gz"
    remote_src: yes
    dest: "{{ ansible_tower_tmp }}"
    creates: "{{ ansible_tower_tmp }}/ansible-tower-setup-bundle-{{ ansible_tower_version }}.el7/setup.sh"

- name: Create inventory file
  template:
    src: inventory.j2
    dest: "{{ ansible_tower_tmp }}/ansible-tower-setup-bundle-{{ ansible_tower_version }}.el7/inventory"
    force: no

- name: Execute installation
  shell: './setup.sh'
  become: yes
  args:
    chdir: "{{ ansible_tower_tmp }}/ansible-tower-setup-bundle-{{ ansible_tower_version }}.el7"

- name: Install Tower license
  become: yes
  copy:
    src: ansible_tower.lic
    dest: /etc/tower/license
    owner: awx
    group: awx
    mode: 0600
