---
- name: Configure the F5s
  hosts: tmos
  connection: local
  gather_facts: False
  tasks:
    - name: Create the http-pool pool
      bigip_pool:
        server: "{{ ansible_host }}"
        user: "{{ network_username }}"
        password: "{{ network_password }}"
        validate_certs: no
        name: "http-pool"

    - name: Add a new node
      bigip_node:
        server: "{{ ansible_host }}"
        user: "{{ network_username }}"
        password: "{{ network_password }}"
        validate_certs: no
        state: "present"
        partition: "Common"
        host: "{{ hostvars[item].ansible_host }}"
        name: "{{ hostvars[item].ansible_host }}"
      when: groups.app_hosts is defined
      with_items: "{{ groups.app_hosts }}"

    - name: Add host to pool member
      bigip_pool_member:
        server: "{{ ansible_host }}"
        user: "{{ network_username }}"
        password: "{{ network_password }}"
        validate_certs: no
        pool: "http-pool"
        partition: "Common"
        host: "{{ hostvars[item].ansible_host }}"
        port: 80
        description: "web server"
        connection_limit: 100
        rate_limit: 50
        ratio: 2
      when: groups.app_hosts is defined
      with_items: "{{ groups.app_hosts }}"

    - name: Add VS on BIG-IP
      bigip_virtual_server:
        server: "{{ ansible_host }}"
        user: "{{ network_username }}"
        password: "{{ network_password }}"
        name: "httpvs"
        destination: "{{ interfaces[1].private_ip_address }}"
        port: 80
        pool: "http-pool"
        snat: Automap
        validate_certs: False

    - debug: msg="The Virtual Server Address is {{ interfaces[1].public_ip_address }}"
